## Define data to be passed to template.
## Prefix images with 'img-' for auto thumb creation.
## Anything defined here will be passed down to template, so go nuts.
title: "It's christmas time"
subtitle: "Lights up!"
img-thumb: "santa.jpg"
