## Define data to be passed to template.
## Prefix images with 'img-' for auto thumb creation.
## Anything defined here will be passed down to template, so go nuts.
title: "Summer Time"
subtitle: "Oh, good sun."
img-thumb: "bag.jpg"
