language: php

php:
  - 5.5

sudo: false

before_script:
  - composer install --no-interaction --prefer-dist

script:
  - php vendor/bin/phpunit --coverage-clover coverage.clover

after_script:
 - php vendor/bin/coveralls -v
