<?php
/** @var $this \Photos\Renderer\Collections */
$collections = $this->getCollections();
?>
<html>
    <head>
        <title>Photos, by qrz.io</title>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name="description" content="" />
        <meta name="keywords" content="" />
    </head>
    <body>
        <h1>Collections</h1>
        <?php foreach ($collections as $collection): ?>
            <a href="<?php echo $collection['path'] ?>">
                <h3><?php echo $collection['title'] ?></h3>
                <img src="<?php echo $collection['path'] . $collection['img-thumb'] ?>" />
            </a>
            <br />
        <?php endforeach; ?>
    </body>
</html>
