<?php
/** @var $this \Photos\Renderer\Collection */
$collection = $this->getCollectionData();
?>
<html>
<head>
    <title>Photos, by qrz.io</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
</head>
<body>
    <h1><?php echo $collection['title'] ?></h1>
    <h2><?php echo $collection['subtitle'] ?></h2>
    <?php foreach ($collection['photos'] as $photo): ?>
        <a href="<?php echo $photo['BigImage'] ?>">
            <img src="<?php echo $photo['Thumbnail'] ?>" />
        </a>
        <a href="<?php echo $photo['RealImage']; ?>">full image</a>
        <br />
    <?php endforeach; ?>
</body>
</html>
